server:
  port: 7002

logging:
  level:
    root: info
    me.blessedsibanda.microservices: debug
    me.blessedsibanda.util: debug

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080