server:
  port: 7001

logging:
  level:
    root: info
    me.blessedsibanda.microservices: debug
    me.blessedsibanda.util: debug

spring:
  data:
    mongodb:
      auto-index-creation: true
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080